//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycebnaia.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.yslygi_client = new HashSet<yslygi_client>();
        }
    
        public int id_client { get; set; }
        public string familiya { get; set; }
        public string imya { get; set; }
        public string otchestvo { get; set; }
        public System.DateTime data_rog { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string pol { get; set; }
        public System.DateTime data_registr { get; set; }
        public string photo { get; set; }
        public Nullable<int> id_tip { get; set; }
    
        public virtual tip_clienta tip_clienta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yslygi_client> yslygi_client { get; set; }
    }
}
