//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycebnaia.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class complimentarnie_tovar
    {
        public int id_complimentarnie_tovar { get; set; }
        public int id_tovar_1 { get; set; }
        public int id_tovar_2 { get; set; }
    
        public virtual tovar tovar { get; set; }
        public virtual tovar tovar1 { get; set; }
    }
}
