//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycebnaia.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodagi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prodagi()
        {
            this.prodagi_yslyg_client = new HashSet<prodagi_yslyg_client>();
        }
    
        public int id_prodag { get; set; }
        public int kolichestvo { get; set; }
        public int id_tovar { get; set; }
        public System.DateTime data_proagi { get; set; }
    
        public virtual tovar tovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodagi_yslyg_client> prodagi_yslyg_client { get; set; }
    }
}
