//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycebnaia.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodagi_yslyg_client
    {
        public int id_prodag_ys_client { get; set; }
        public int id_yslyg_client { get; set; }
        public int id_prodag { get; set; }
    
        public virtual prodagi prodagi { get; set; }
        public virtual yslygi_client yslygi_client { get; set; }
    }
}
