//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycebnaia.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class sezonue_tovar
    {
        public int id_sezonie_tovar { get; set; }
        public int id_sezon { get; set; }
        public int id_tovar { get; set; }
    
        public virtual sezon sezon { get; set; }
        public virtual tovar tovar { get; set; }
    }
}
