//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycebnaia.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sotrudnik()
        {
            this.yslygi_sotrudnika = new HashSet<yslygi_sotrudnika>();
        }
    
        public int id_sotrydnika { get; set; }
        public string familiya { get; set; }
        public string imya { get; set; }
        public string otchestvo { get; set; }
        public int seriya_pasporta { get; set; }
        public int nomer_pasporta { get; set; }
        public int id_podrazdeleniya { get; set; }
        public string pol { get; set; }
        public double koeffic_oplati { get; set; }
        public System.DateTime data_rog { get; set; }
        public int id_kategorii { get; set; }
    
        public virtual kategoriya_sotrudnika kategoriya_sotrudnika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yslygi_sotrudnika> yslygi_sotrudnika { get; set; }
    }
}
