//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycebnaia.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tovar()
        {
            this.complimentarnie_tovar = new HashSet<complimentarnie_tovar>();
            this.complimentarnie_tovar1 = new HashSet<complimentarnie_tovar>();
            this.prodagi = new HashSet<prodagi>();
            this.sezonue_tovar = new HashSet<sezonue_tovar>();
            this.sklad = new HashSet<sklad>();
        }
    
        public int id_tovar { get; set; }
        public string xaracteristika { get; set; }
        public string opisanie { get; set; }
        public string photo { get; set; }
        public string naimenovanie { get; set; }
        public string kategoriya { get; set; }
        public double stoimost { get; set; }
        public string paznovidnost { get; set; }
        public double visota { get; set; }
        public double shirina { get; set; }
        public double dlina { get; set; }
        public string glavnoe_izobragenie { get; set; }
        public string dop_photo { get; set; }
        public int id_proizvod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<complimentarnie_tovar> complimentarnie_tovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<complimentarnie_tovar> complimentarnie_tovar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodagi> prodagi { get; set; }
        public virtual proizvoditel proizvoditel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sezonue_tovar> sezonue_tovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sklad> sklad { get; set; }
    }
}
