//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ycebnaia.Bd
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class yslygi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yslygi()
        {
            this.yslygi_client = new HashSet<yslygi_client>();
            this.yslygi_sotrudnika = new HashSet<yslygi_sotrudnika>();
        }

        public string PriceSkidka
        {
            get
            {
                if (skidka != 0)
                {
                    double p = (double)(tcena - tcena * skidka / 100);
                    return $"{p:F2} рублей за {dlitelnost} минут";
                }
                else
                    return $"{tcena:F2} рублей за {dlitelnost} минут";
            }
        }

        public string Colorbr
        {
            get
            {
                if (skidka > 0)
                    return "greenYellow";
                else
                    return "White";
            }
        }


        public string GetPhoto
        {
            get
            {
                if (photo is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + photo.Trim();
            }
        }

        public string GetVisible
        {
            get
            {
                if (skidka == 0)
                    return "Collapsed";
                else
                    return "Visible";
            }
        }


        public int id_yslyg { get; set; }
        public string naimenovanue { get; set; }
        public Nullable<double> skidka { get; set; }
        public string photo { get; set; }
        public int dlitelnost { get; set; }
        public double tcena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yslygi_client> yslygi_client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yslygi_sotrudnika> yslygi_sotrudnika { get; set; }
    }
}
